version: '3.5'
services:
  consumer-dsc:
    container_name: consumer-dsc
    build:
      context: ../../
      dockerfile: docker/app/Dockerfile
      args:
        ENV: ${NODE_ENV}
    restart: unless-stopped
    tty: true
    volumes:
      - '../../src/:/usr/src/app/src'
      - './config.json:/usr/src/app/src/config.json'
    ports:
      - "3021:3000"
    links:
      - mongodb2
    env_file:
      - .env
    networks:
      - consumer-dsc
      - consumer-api
      - connectors


  mongodb2:
    container_name: "consumer-dsc-mongodb"
    build:
      context: ../../
      dockerfile: docker/mongodb/Dockerfile
    #    Uncomment to connect mongodb container to mongo compass or another service
    ports:
      - "27016:27017"
    networks:
      - consumer-dsc

networks:
  consumer-dsc:
    external: false
    name: consumer-dsc
  connectors:
    external: false
    name: connectors
  consumer-api:
    external: true