version: '3.5'
services:
  provider-dsc:
    container_name: provider-dsc
    build:
      context: ../../
      dockerfile: docker/app/Dockerfile
      args:
        ENV: ${NODE_ENV}
#    command: npm run dev
    restart: unless-stopped
    tty: true
    volumes:
      - '../../src/:/usr/src/app/src'
      - './config.json:/usr/src/app/src/config.json'
    ports:
      - "3011:3000"
    links:
      - mongodb2
    env_file:
      - .env
    networks:
      - provider-dsc
      - provider-api
      - connectors


  mongodb2:
    container_name: "provider-dsc-mongodb"
    build:
      context: ../../
      dockerfile: docker/mongodb/Dockerfile
    #    Uncomment to connect mongodb container to mongo compass or another service
    ports:
      - "27021:27017"
    networks:
      - provider-dsc

networks:
  provider-dsc:
    external: false
    name: provider-dsc
  connectors:
    external: false
    name: connectors
  provider-api:
    external: true